export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const FETCH_CUSTOMERS_SUCCESS = "FETCH_CUSTOMERS_SUCCESS";
export const FETCH_CUSTOMER_FAIL = "FETCH_CUSTOMER_FAIL";
export const FETCH_CUSTOMER_LOADING = "FETCH_CUSTOMER_LOADING";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
